#!/usr/bin/env bash
#
# Generates / refreshes the Homebrew cask for VizhiOCR in a SEPARATE tap repo that lives
# OUTSIDE this repo (default ../homebrew-vizhiocr). It's called automatically at the end of
# a successful scripts/notarize.sh run, so the cask's version + sha256 always match the DMG
# that was just notarized and stapled.
#
# A Homebrew tap MUST be its own git repo named `homebrew-<something>`, with cask files under
# `Casks/`. If the tap directory doesn't exist yet, this scaffolds it from scratch
# (Casks/ + README + the .rb). It deliberately does NOT touch git — you commit & push the tap
# yourself (see the hints printed at the end).
#
# ┌─ EDIT THESE before you publish ────────────────────────────────────────────┐
# │ Placeholders so you can swap in real repo details quickly. Either edit them  │
# │ here, or export GH_OWNER / GH_REPO / HOMEPAGE in the environment.            │
GH_OWNER="${GH_OWNER:-purple-glass-dev}"     # GitHub username/org that hosts the releases
GH_REPO="${GH_REPO:-vizhi-ocr}"              # the APP repo whose Releases hold the .dmg
HOMEPAGE="${HOMEPAGE:-https://github.com/$GH_OWNER/$GH_REPO}"
# └─────────────────────────────────────────────────────────────────────────────┘
#
# Usage:
#   scripts/update-cask.sh [path/to/DMG]      # DMG defaults to dist/VizhiOCR-<version>.dmg
#   TAP_DIR=../homebrew-vizhiocr scripts/update-cask.sh
#   GH_OWNER=arvind GH_REPO=vizhi-ocr scripts/update-cask.sh
set -euo pipefail
cd "$(dirname "$0")/.."
REPO_ROOT="$PWD"

# --- Facts about the app (kept in sync with build-app.sh / Package.swift) -----
APP_NAME="VizhiOCR"
CASK_TOKEN="vizhi-ocr"                        # `brew install --cask vizhi-ocr`
BUNDLE_ID="com.vizhi.ocr"                     # build-app.sh: BUNDLE_ID default
MIN_MACOS="sequoia"                           # Package.swift: .macOS(.v15) == Sequoia

VERSION="${VERSION:-$("$REPO_ROOT/scripts/version.sh")}"   # latest vX.Y.Z tag, `v` stripped
DMG="${1:-$REPO_ROOT/dist/$APP_NAME-$VERSION.dmg}"
TAP_DIR="${TAP_DIR:-$REPO_ROOT/../homebrew-vizhiocr}"
CASK_DIR="$TAP_DIR/Casks"
CASK_FILE="$CASK_DIR/$CASK_TOKEN.rb"

# --- Preflight ---------------------------------------------------------------
if [ ! -f "$DMG" ]; then
  echo "!! DMG not found: $DMG" >&2
  echo "   Build it first (scripts/notarize.sh) or pass the DMG path as the first argument." >&2
  exit 1
fi

SHA256="$(shasum -a 256 "$DMG" | awk '{print $1}')"

# --- Scaffold the tap if it doesn't exist yet --------------------------------
if [ ! -d "$TAP_DIR" ]; then
  echo "==> Tap not found — scaffolding a fresh one at: $TAP_DIR"
  mkdir -p "$CASK_DIR"
  cat > "$TAP_DIR/README.md" <<EOF
# homebrew-vizhiocr

Homebrew tap for [VizhiOCR]($HOMEPAGE) — an on-device OCR menu bar app for macOS.

## Install

\`\`\`sh
brew install --cask $GH_OWNER/vizhiocr/$CASK_TOKEN
\`\`\`

Or tap first, then install:

\`\`\`sh
brew tap $GH_OWNER/vizhiocr
brew install --cask $CASK_TOKEN
\`\`\`

## Upgrade

\`\`\`sh
brew upgrade --cask $CASK_TOKEN
\`\`\`

_The cask in \`Casks/\` is generated by \`scripts/update-cask.sh\` in the app repo on each
notarized release — edit it there, not here._
EOF
else
  mkdir -p "$CASK_DIR"   # tap exists but Casks/ might not
fi

# Resolve to an absolute path now that the dir exists (for tidy output).
TAP_DIR="$(cd "$TAP_DIR" && pwd)"
CASK_FILE="$TAP_DIR/Casks/$CASK_TOKEN.rb"

# --- Write the cask ----------------------------------------------------------
# Note: `#{version}` below is Ruby string interpolation evaluated by Homebrew, NOT shell —
# it stays literal here so the url line never changes between releases (only version + sha256
# do). $APP_NAME / $GH_OWNER / etc. ARE expanded by the shell.
echo "==> Writing cask: $CASK_FILE"
cat > "$CASK_FILE" <<EOF
cask "$CASK_TOKEN" do
  version "$VERSION"
  sha256 "$SHA256"

  url "https://github.com/$GH_OWNER/$GH_REPO/releases/download/v#{version}/$APP_NAME-#{version}.dmg"
  name "Vizhi OCR"
  desc "On-device OCR menu bar app powered by MLX vision models"
  homepage "$HOMEPAGE"

  depends_on macos: ">= :$MIN_MACOS"

  app "$APP_NAME.app"

  zap trash: [
    "~/Library/Application Support/$APP_NAME",
    "~/Library/Caches/$APP_NAME",
    "~/Library/Caches/$BUNDLE_ID",
    "~/Library/Preferences/$BUNDLE_ID.plist",
    "~/Library/Saved Application State/$BUNDLE_ID.savedState",
  ]
end
EOF

# --- Summary + next steps ----------------------------------------------------
echo "==> Cask updated:"
echo "      token   : $CASK_TOKEN"
echo "      version : $VERSION"
echo "      sha256  : $SHA256"
echo "      dmg     : $DMG"

if [ "$GH_OWNER" = "REPLACE_ME_OWNER" ]; then
  echo "!! Placeholder repo details still in use — edit GH_OWNER/GH_REPO in scripts/update-cask.sh" >&2
  echo "   (or export them) before publishing, then re-run. The url/homepage above are not real yet." >&2
fi

echo "==> Next (git is yours to run):"
echo "      cd $TAP_DIR"
echo "      git add Casks/$CASK_TOKEN.rb README.md && git commit -m \"$CASK_TOKEN $VERSION\" && git push"
echo "   Tip: sanity-check with  brew audit --cask $CASK_FILE"
